// Predefined credentials - In production, this should be more secure
export const CREDENTIALS = {
  
  admin1: { password: 'admin123', role: 'admin' as const },
  Barath: { password: '123', role: 'admin' as const },
  Shameer: { password: '123', role: 'admin' as const },
  nuthalapati_nikhil: { password: '123', role: 'student' as const },
  owais_mohammed_khan_f: { password: '123', role: 'student' as const },
  periyaswamy_vignesh: { password: '123', role: 'student' as const },
  sabarinathan_m: { password: '123', role: 'student' as const },
  harikaramuthukumar_m: { password: '123', role: 'student' as const },
  abiram_r: { password: '123', role: 'student' as const },
  akash_k: { password: '123', role: 'student' as const },
  aswin_ananth_s: { password: '123', role: 'student' as const },
  avula_vijay_kumar: { password: '123', role: 'student' as const },
  muthumani_d: { password: '123', role: 'student' as const },
  dharaneesh_v: { password: '123', role: 'student' as const },
  dhayananth_r: { password: '123', role: 'student' as const },
  haribalan_u: { password: '123', role: 'student' as const },
  che_pradeep: { password: '123', role: 'student' as const },
  lakshmikanthan_a: { password: '123', role: 'student' as const },
  manoj_kumar_n: { password: '123', role: 'student' as const },
  muthu_s: { password: '123', role: 'student' as const },
  niranjan_s_s: { password: '123', role: 'student' as const },
  nivas_s: { password: '123', role: 'student' as const },
  santhosh_kumar_s: { password: '123', role: 'student' as const },
  shanmuga_krishnan_s_m: { password: '123', role: 'student' as const },
  shanmuganathan_s_s: { password: '123', role: 'student' as const },
  rakesh_k: { password: '123', role: 'student' as const },
  shyam_francis_t_: { password: '123', role: 'student' as const },
  siddartha_mariappan_s: { password: '123', role: 'student' as const },
  teij_aswin_s: { password: '123', role: 'student' as const },
  thejeswar_g: { password: '123', role: 'student' as const },
  'a.g.amudieshwar': { password: '123', role: 'student' as const },
  sagar_m: { password: '123', role: 'student' as const },
  chandrahaas_k: { password: '123', role: 'student' as const },
  canany_sreeram: { password: '123', role: 'student' as const },
  derala_chethan_kumar: { password: '123', role: 'student' as const },
  jeelaga_chenchu_rakesh: { password: '123', role: 'student' as const },
  jonnalagadda_aakash: { password: '123', role: 'student' as const },
  kishore_m: { password: '123', role: 'student' as const },
  padarthi_saketh: { password: '123', role: 'student' as const },
  lanka_viswaksane_reddy: { password: '123', role: 'student' as const },
  muli_mohan_reddy: { password: '123', role: 'student' as const },
  padarthi_dheeraj: { password: '123', role: 'student' as const },
  kollipara_sai_charan: { password: '123', role: 'student' as const },
  palem_deshik_akshendra_kumar: { password: '123', role: 'student' as const },
  ramireddy_sai_naveen_reddy: { password: '123', role: 'student' as const },
  ravipudi_rakesh_chowdary: { password: '123', role: 'student' as const },
  satwik_reddy_k: { password: '123', role: 'student' as const },
  shivasubramanian_a: { password: '123', role: 'student' as const },
  boddu_jashvanth: { password: '123', role: 'student' as const },
  sudharsan_raju: { password: '123', role: 'student' as const },
  tharun_prasath_b: { password: '123', role: 'student' as const },
  thiruvarul_k: { password: '123', role: 'student' as const },
  'thokala.jaya_adithya': { password: '123', role: 'student' as const },
  uppalapati_bhargav: { password: '123', role: 'student' as const },
  vemula_srinikhil: { password: '123', role: 'student' as const },
  abishek_t: { password: '123', role: 'student' as const },
  dharun_s: { password: '123', role: 'student' as const },
  manigandan_r: { password: '123', role: 'student' as const },
  jagan_s: { password: '123', role: 'student' as const },
  rahul_prasath_r: { password: '123', role: 'student' as const },
  sriram_s: { password: '123', role: 'student' as const },
  tharunkumar_b: { password: '123', role: 'student' as const },
  vajay_baskar_k: { password: '123', role: 'student' as const },
  abisheik_s: { password: '123', role: 'student' as const },
  edric_vaz_f: { password: '123', role: 'student' as const },
  sunilkumar_s: { password: '123', role: 'student' as const },
  kamesh_p: { password: '123', role: 'student' as const },
  kirthik_adithya_r: { password: '123', role: 'student' as const },
  pranit_r: { password: '123', role: 'student' as const },
  sesha_rengan_s: { password: '123', role: 'student' as const },
  vethanth_s: { password: '123', role: 'student' as const },
  yugandhar_d: { password: '123', role: 'student' as const },
  jawahar_babu_n: { password: '123', role: 'student' as const },
  naveen_a: { password: '123', role: 'student' as const },
  'amudhan_m.': { password: '123', role: 'student' as const },
  maadhav_m: { password: '123', role: 'student' as const },
  avineshwaran_a: { password: '123', role: 'student' as const },
  balaji_m_r: { password: '123', role: 'student' as const },
  bharanidharan_r: { password: '123', role: 'student' as const },
  bhargav: { password: '123', role: 'student' as const },
  chris_alan: { password: '123', role: 'student' as const },
  devak_s: { password: '123', role: 'student' as const },
  dinesh_v: { password: '123', role: 'student' as const },
  giridharan_b_g: { password: '123', role: 'student' as const },
  hanumesh_k: { password: '123', role: 'student' as const },
  harshak_k_c: { password: '123', role: 'student' as const },
  rishi_kamal: { password: '123', role: 'student' as const },
  josewa_aghai_davidson: { password: '123', role: 'student' as const },
  kamaleshwaran_r: { password: '123', role: 'student' as const },
  ragul_k: { password: '123', role: 'student' as const },
  kashpin_anto_m: { password: '123', role: 'student' as const },
  kiran_aneruthya_g_v: { password: '123', role: 'student' as const },
  sriram_n_s: { password: '123', role: 'student' as const },
  manish_v: { password: '123', role: 'student' as const },
  rajakumaraguru_k_j: { password: '123', role: 'student' as const },
  naveen_kumar_a: { password: '123', role: 'student' as const },
  pradeep_jayanth_s: { password: '123', role: 'student' as const },
  priyan_joseph_i: { password: '123', role: 'student' as const },
  puvvada_venkata_sainadh: { password: '123', role: 'student' as const },
  karneshkumar_s: { password: '123', role: 'student' as const },
  ramesh_praveen_kumar: { password: '123', role: 'student' as const },
  rohith_kumar_g: { password: '123', role: 'student' as const },
  sannareddy_sushvardhan_reddy: { password: '123', role: 'student' as const },
  james_s: { password: '123', role: 'student' as const },
  raja_deepak_s: { password: '123', role: 'student' as const },
  chanakyan_t: { password: '123', role: 'student' as const },
  madhiraju_jyothi_prasad: { password: '123', role: 'student' as const },
  mithunkumar_k_t: { password: '123', role: 'student' as const },
  anandhakrishnan_b: { password: '123', role: 'student' as const },
  dhesinguraja_p: { password: '123', role: 'student' as const },
  sam_meshak_p: { password: '123', role: 'student' as const },
  hariprasath_m: { password: '123', role: 'student' as const },
  kabin_subbinath_a: { password: '123', role: 'student' as const },
  abisheik_c: { password: '123', role: 'student' as const },
  vetri_murugan_k: { password: '123', role: 'student' as const },
  sanjit_kumar_s: { password: '123', role: 'student' as const },
  sam_haris_t: { password: '123', role: 'student' as const },
  shanmugapriyan_r: { password: '123', role: 'student' as const },
  sriram_h: { password: '123', role: 'student' as const },
  thamizharasan_s: { password: '123', role: 'student' as const },
  kishore_k: { password: '123', role: 'student' as const },
  yashwan_r: { password: '123', role: 'student' as const },
  yelam_praneeth_sriram: { password: '123', role: 'student' as const },
  yendluri_harshavardhan: { password: '123', role: 'student' as const },
  dhayanithie_i_a: { password: '123', role: 'student' as const },
  palanivel_s: { password: '123', role: 'student' as const },
  madhan_rahul_g: { password: '123', role: 'student' as const },
  ananda_krishna__: { password: '123', role: 'student' as const },
  jawahar: { password: '123', role: 'student' as const },
  abishek_s: { password: '123', role: 'student' as const },
  suriya_m: { password: '123', role: 'student' as const },
  yogeshwaran_n: { password: '123', role: 'student' as const },
  thirumalai_d: { password: '123', role: 'student' as const },
  naveen_harish_s_k: { password: '123', role: 'student' as const },
  monish_m_s: { password: '123', role: 'student' as const },
  muthamizhselvan_s: { password: '123', role: 'student' as const },
  nishal_priyan_a: { password: '123', role: 'student' as const },
  nithish_v: { password: '123', role: 'student' as const },
  rakesh_n: { password: '123', role: 'student' as const },
  rohith_s: { password: '123', role: 'student' as const },
  samier_ahmed_j: { password: '123', role: 'student' as const },
  sanjay_m: { password: '123', role: 'student' as const },
  velan_s: { password: '123', role: 'student' as const },
  gurusaran_v_s: { password: '123', role: 'student' as const },
  sathish_p_s: { password: '123', role: 'student' as const },
  santhosh_prem_p: { password: '123', role: 'student' as const },
  george_selvin_s: { password: '123', role: 'student' as const },
  jegan_m: { password: '123', role: 'student' as const },
  darshan_k: { password: '123', role: 'student' as const },
  sakthikesh_n: { password: '123', role: 'student' as const },
  sri_sathiya_narayanan_k: { password: '123', role: 'student' as const },
  ashuwanth_s: { password: '123', role: 'student' as const },
  abdul_hameed_a: { password: '123', role: 'student' as const },
  namish_a: { password: '123', role: 'student' as const },
  kavin_raj_n: { password: '123', role: 'student' as const },
  hemnath_s: { password: '123', role: 'student' as const },
  dharun_raj_d: { password: '123', role: 'student' as const },
  duraimurugan_s: { password: '123', role: 'student' as const },
  jagadhesan_s: { password: '123', role: 'student' as const },
  nikhil_siddharth_r: { password: '123', role: 'student' as const },
  ram_kishore_kp: { password: '123', role: 'student' as const },
  rohan_v_s: { password: '123', role: 'student' as const },
  subikeesh_m: { password: '123', role: 'student' as const },
  tharnesh_s: { password: '123', role: 'student' as const },
  vijeya_sharathi_ks: { password: '123', role: 'student' as const },
  muthusuresh_n: { password: '123', role: 'student' as const },
  balaji_p: { password: '123', role: 'student' as const },
  rajesh_e: { password: '123', role: 'student' as const },
  naveen_s: { password: '123', role: 'student' as const },
  dhinakaran_k: { password: '123', role: 'student' as const },
  seenuvasan_r: { password: '123', role: 'student' as const },
  rasool_m: { password: '123', role: 'student' as const },
  prabakaran_r: { password: '123', role: 'student' as const },
  maheshwaran_s: { password: '123', role: 'student' as const },
  vaikeshmathan_s: { password: '123', role: 'student' as const },
  ravikumar_r: { password: '123', role: 'student' as const },
  sathish_j: { password: '123', role: 'student' as const },
  upanishath_b: { password: '123', role: 'student' as const },
  jaiganesh_p: { password: '123', role: 'student' as const },
  gowthama_inish_kumar_v: { password: '123', role: 'student' as const },
  chitharanjan_e: { password: '123', role: 'student' as const },
  mukesh_r: { password: '123', role: 'student' as const },
  abdus_salaam_a: { password: '123', role: 'student' as const },
  prasanna_e: { password: '123', role: 'student' as const },
  pavithran_v: { password: '123', role: 'student' as const },
  tamilmaran: { password: '123', role: 'student' as const },
  baranidharan_s: { password: '123', role: 'student' as const },
  shylendhar_m: { password: '123', role: 'student' as const },
  nithishkumar_s: { password: '123', role: 'student' as const },
  gokulram_p_r: { password: '123', role: 'student' as const },
  vetrivel_a: { password: '123', role: 'student' as const },
  nandhikesavan_: { password: '123', role: 'student' as const },
  yuvaneshan_v: { password: '123', role: 'student' as const },
  dheepak_s: { password: '123', role: 'student' as const },
  nikil_raj_k: { password: '123', role: 'student' as const },
  sachin_kumar_k: { password: '123', role: 'student' as const },
  arutselvam_v: { password: '123', role: 'student' as const },
  sri_harish_a: { password: '123', role: 'student' as const },
  praveen_kumar_v: { password: '123', role: 'student' as const },
  nasar_ali_j: { password: '123', role: 'student' as const },
  reshwanth_s_b: { password: '123', role: 'student' as const },
  sarveshwaran_s: { password: '123', role: 'student' as const },
  mohandas_e: { password: '123', role: 'student' as const },
  mohanakrishnan_m: { password: '123', role: 'student' as const },
  muralidharan_k: { password: '123', role: 'student' as const },
  'sakthivel.r': { password: '123', role: 'student' as const },
  ahmed_aslam_wajith: { password: '123', role: 'student' as const },
  kathiravan_a: { password: '123', role: 'student' as const },
  sunithkumar_m: { password: '123', role: 'student' as const },
  kavipriyan_p: { password: '123', role: 'student' as const },
  rahul_m_k: { password: '123', role: 'student' as const },
  harishbabu_a: { password: '123', role: 'student' as const },
  harivasan_s: { password: '123', role: 'student' as const },
  thendral_raja_m_j: { password: '123', role: 'student' as const },
  devaprakash_j: { password: '123', role: 'student' as const },
  aathi_seshan_j_k: { password: '123', role: 'student' as const },
  vetrivel_s: { password: '123', role: 'student' as const },
  atheesh_l: { password: '123', role: 'student' as const },
  ayyanar_s: { password: '123', role: 'student' as const },
  bavan_j: { password: '123', role: 'student' as const },
  suryanarayanan: { password: '123', role: 'student' as const },
  dilish_r: { password: '123', role: 'student' as const },
  kamalesh_s: { password: '123', role: 'student' as const },
  mohammed_anas_m_h: { password: '123', role: 'student' as const },
  mugesh_m: { password: '123', role: 'student' as const },
  mugunthan_m: { password: '123', role: 'student' as const },
  ruban_m: { password: '123', role: 'student' as const },
  akilan_g_l: { password: '123', role: 'student' as const },
  giri_v: { password: '123', role: 'student' as const },
  sanjai_r: { password: '123', role: 'student' as const },
  shanmugapriyan_g: { password: '123', role: 'student' as const },
  dhilip_kumar_r: { password: '123', role: 'student' as const },
  vetrivel_n: { password: '123', role: 'student' as const },
  sheik_abdul_khader_t: { password: '123', role: 'student' as const },
  santhosh_m_n: { password: '123', role: 'student' as const },
  monish_r: { password: '123', role: 'student' as const },
  mohamed_harrish: { password: '123', role: 'student' as const },
  dharani_vendan_s: { password: '123', role: 'student' as const },
  nishal_b: { password: '123', role: 'student' as const },
  thiyaneswaran_n: { password: '123', role: 'student' as const },
  surya_m: { password: '123', role: 'student' as const },
  balakoushik_r: { password: '123', role: 'student' as const },
  nishanth_g: { password: '123', role: 'student' as const },
  aswantharam_r: { password: '123', role: 'student' as const },
  suryaprakash_i: { password: '123', role: 'student' as const },
  vishwa_k: { password: '123', role: 'student' as const },
  pramoth_m: { password: '123', role: 'student' as const },
  keerthivasan_s: { password: '123', role: 'student' as const },
  pablo_neruda_k: { password: '123', role: 'student' as const },
  magadeva: { password: '123', role: 'student' as const },
  ramalingam_k: { password: '123', role: 'student' as const },
  jaslin_dejo: { password: '123', role: 'student' as const },
  karthick_d: { password: '123', role: 'student' as const },
  vijayathithan_m: { password: '123', role: 'student' as const },
  prasanna_balaji_r: { password: '123', role: 'student' as const },
  dheenadayalan_b: { password: '123', role: 'student' as const },
  manjamuthu_p: { password: '123', role: 'student' as const },
  vishwa_r: { password: '123', role: 'student' as const },
  dheenadhayalan_s: { password: '123', role: 'student' as const },
  thirukumaran_s: { password: '123', role: 'student' as const },
  udhayansamy_vel_p_j: { password: '123', role: 'student' as const },
  aswanthar_m: { password: '123', role: 'student' as const },
  idhayathulla_a: { password: '123', role: 'student' as const },
  rithik_a: { password: '123', role: 'student' as const },
  tamilselvan_d: { password: '123', role: 'student' as const },
  thirumalai_k: { password: '123', role: 'student' as const },
  devaprabu_g: { password: '123', role: 'student' as const },
  bhuvaneshwaran_s: { password: '123', role: 'student' as const },
  nikhil_karthick_t: { password: '123', role: 'student' as const },
  siva_visveshwar_v_j: { password: '123', role: 'student' as const },
  dinagaran_n: { password: '123', role: 'student' as const },
  masana_moorthi_n: { password: '123', role: 'student' as const },
  mohammed_azeem_v_s: { password: '123', role: 'student' as const },
  gokulnath__p: { password: '123', role: 'student' as const },
  gokul_s: { password: '123', role: 'student' as const },
  paramasivan_siva_e: { password: '123', role: 'student' as const },
  dharanishkumar_v: { password: '123', role: 'student' as const },
  gokul_raj_y: { password: '123', role: 'student' as const },
  kishore_j: { password: '123', role: 'student' as const },
  kalaivanan_s: { password: '123', role: 'student' as const },
  harish_c: { password: '123', role: 'student' as const },
  mayakkannan_v: { password: '123', role: 'student' as const },
  syed_salman_a: { password: '123', role: 'student' as const },
  kishorkannan_v: { password: '123', role: 'student' as const },
  raguraman_m: { password: '123', role: 'student' as const },
  gowthaman_a: { password: '123', role: 'student' as const },
  kabilan: { password: '123', role: 'student' as const },
  pragatheeshwaran_g: { password: '123', role: 'student' as const },
  dharaneeshwar_p: { password: '123', role: 'student' as const },
  a_kamalakannan: { password: '123', role: 'student' as const },
  gururajasekar_p: { password: '123', role: 'student' as const },
  kiruthik_s: { password: '123', role: 'student' as const },
  ponperumal_m: { password: '123', role: 'student' as const },
  madeshwaran_r_m: { password: '123', role: 'student' as const },
  lingeshwaram_s_r: { password: '123', role: 'student' as const },
  shafeer_ahamed_m: { password: '123', role: 'student' as const },
  karthikraj_s: { password: '123', role: 'student' as const },
  mohan_raj_v: { password: '123', role: 'student' as const },
  sivamani_d: { password: '123', role: 'student' as const },
  vijaya_chandilya_g: { password: '123', role: 'student' as const },
  mohammed_anas_j: { password: '123', role: 'student' as const },
  ponneelan_p: { password: '123', role: 'student' as const },
  praveen_d: { password: '123', role: 'student' as const },
  vijayan_e: { password: '123', role: 'student' as const },
  ranjith_r: { password: '123', role: 'student' as const },
  rajasanthosh_g: { password: '123', role: 'student' as const },
  gokulnath_r: { password: '123', role: 'student' as const },
  sanjay_s_v: { password: '123', role: 'student' as const },
  sakthidhasan_m: { password: '123', role: 'student' as const },
  hari_prasath_e: { password: '123', role: 'student' as const },
  vetri_vendhan_m: { password: '123', role: 'student' as const },
  nivesh_kavi_priyan_j: { password: '123', role: 'student' as const },
  sriram_r: { password: '123', role: 'student' as const },
  dharun_k: { password: '123', role: 'student' as const },
  sivasankar_k: { password: '123', role: 'student' as const },
  sivamurugan_a: { password: '123', role: 'student' as const },
  jaganraj_p: { password: '123', role: 'student' as const },
  veeramani_muthu_g: { password: '123', role: 'student' as const },
  levin_ray_j: { password: '123', role: 'student' as const },
  mithunkumar_s: { password: '123', role: 'student' as const },
  mohamed_arshad_k_a: { password: '123', role: 'student' as const },
  marilesh_kabilan_m: { password: '123', role: 'student' as const },
  bhavani_sankar_m: { password: '123', role: 'student' as const },
  lukesh_g: { password: '123', role: 'student' as const },
  thibin_r: { password: '123', role: 'student' as const },
  vishva_v: { password: '123', role: 'student' as const },
  krishnan_m: { password: '123', role: 'student' as const },
  p_a_nandeesh: { password: '123', role: 'student' as const },
  vishal_: { password: '123', role: 'student' as const },
  sarannithish_v: { password: '123', role: 'student' as const },
  raja_saravana_priyan_s: { password: '123', role: 'student' as const },
  deepak_k_k_m: { password: '123', role: 'student' as const },
  vasanth_g: { password: '123', role: 'student' as const },
  hariprakash_n: { password: '123', role: 'student' as const },
  kathirvelan_rm: { password: '123', role: 'student' as const },
  parthasarathi_m: { password: '123', role: 'student' as const },
  nithin_g: { password: '123', role: 'student' as const },
  tamilselvan_m: { password: '123', role: 'student' as const },
  tamizharasan_a: { password: '123', role: 'student' as const },
  solairaj_r: { password: '123', role: 'student' as const },
  gokulakrishnan_v: { password: '123', role: 'student' as const },
  mohamed_imthiyas_k: { password: '123', role: 'student' as const },
  karthikeyan_d: { password: '123', role: 'student' as const },
  panprasu_k: { password: '123', role: 'student' as const },
  mohamed_shameem_m: { password: '123', role: 'student' as const },
  madhanraj_v: { password: '123', role: 'student' as const },
  sridhar_a: { password: '123', role: 'student' as const },
  arul_kumar_v: { password: '123', role: 'student' as const },
  mohamed_mufrih_s: { password: '123', role: 'student' as const },
  parameshwaran_l: { password: '123', role: 'student' as const },
  ragul_p: { password: '123', role: 'student' as const },
  abhilash_m: { password: '123', role: 'student' as const },
  suriya_lithesh_g: { password: '123', role: 'student' as const },
  sasikumar_m: { password: '123', role: 'student' as const },
  sudharsan_s_r: { password: '123', role: 'student' as const },
  venugopal_r: { password: '123', role: 'student' as const },
  anbuselvan_m: { password: '123', role: 'student' as const },
  kamaleshwaran_p: { password: '123', role: 'student' as const },
  vinayak_ram_kanniyan: { password: '123', role: 'student' as const },
  yogesh_a: { password: '123', role: 'student' as const },
  ajay_m: { password: '123', role: 'student' as const },
  rajavarman_r: { password: '123', role: 'student' as const },
  mohamed_afsal: { password: '123', role: 'student' as const },
  mowlishwaran_r: { password: '123', role: 'student' as const },
  inbarasan_p: { password: '123', role: 'student' as const },
  balasubramani_s: { password: '123', role: 'student' as const },
  hemachandar_j: { password: '123', role: 'student' as const },
  vigneshwar_s: { password: '123', role: 'student' as const },
  akash_s: { password: '123', role: 'student' as const },
  sanjay_kumar_m_p: { password: '123', role: 'student' as const },
  kalaiyarasu_c_m: { password: '123', role: 'student' as const },
  gopi_p: { password: '123', role: 'student' as const },
  rajarajan: { password: '123', role: 'student' as const },
  madhan_kumar_s: { password: '123', role: 'student' as const },
  nandha_krishnan_m: { password: '123', role: 'student' as const },
  essanth_sarvajith_r_k: { password: '123', role: 'student' as const },
  rajasekar_r: { password: '123', role: 'student' as const },
  sabarish_a: { password: '123', role: 'student' as const },
  rahul_v: { password: '123', role: 'student' as const },
  santhosh_r: { password: '123', role: 'student' as const },
  sharavanan_r: { password: '123', role: 'student' as const },
  tharunmahesh_: { password: '123', role: 'student' as const },
  mohammed_bassil_b: { password: '123', role: 'student' as const },
  sivaramakrishnan: { password: '123', role: 'student' as const },
  sridhar_t: { password: '123', role: 'student' as const },
  barath_r: { password: '123', role: 'student' as const },
  harish_b: { password: '123', role: 'student' as const },
  naveenkumar_v_k: { password: '123', role: 'student' as const },
  karthick_raja_v: { password: '123', role: 'student' as const },
  mohammed_shameer_a: { password: '123', role: 'student' as const },
  sarath_r: { password: '123', role: 'student' as const },
  ahamed_m: { password: '123', role: 'student' as const },
  ajithkumar_d: { password: '123', role: 'student' as const },
  arunagiri_r: { password: '123', role: 'student' as const },
  mukesh_p: { password: '123', role: 'student' as const },
  k_a_kaushik: { password: '123', role: 'student' as const },
  mohamed_ratheef_r: { password: '123', role: 'student' as const },
  rishi_k: { password: '123', role: 'student' as const },
  karthick_k: { password: '123', role: 'student' as const },
  saravana_kumar_n: { password: '123', role: 'student' as const },
  sharavanakumar_r: { password: '123', role: 'student' as const },
  elumalai: { password: '123', role: 'student' as const },
  ragulganesh_v: { password: '123', role: 'student' as const },
  lokesh_s: { password: '123', role: 'student' as const },
  kishorekumar: { password: '123', role: 'student' as const },
  nithish_s: { password: '123', role: 'student' as const },
  bharathraj_k: { password: '123', role: 'student' as const },
  akshay_rr: { password: '123', role: 'student' as const },
  'm._merfin': { password: '123', role: 'student' as const },
  parthipan_l: { password: '123', role: 'student' as const },
  sivagurunathan_p: { password: '123', role: 'student' as const },
  nithin_t: { password: '123', role: 'student' as const },
  abhinesh: { password: '123', role: 'student' as const },
  arundevan_d: { password: '123', role: 'student' as const },
  pradap_s: { password: '123', role: 'student' as const },
  sakthiganesh_s: { password: '123', role: 'student' as const },
  harish: { password: '123', role: 'student' as const },
  bhargava_bharaneesh: { password: '123', role: 'student' as const },
  hariharan_d: { password: '123', role: 'student' as const },
  lakshman_g: { password: '123', role: 'student' as const },
  naresh_varma_s: { password: '123', role: 'student' as const },
  navaneethan_r: { password: '123', role: 'student' as const },
  anbarasan_j: { password: '123', role: 'student' as const },
  harshal_sam_a: { password: '123', role: 'student' as const },
  jagannathan_s: { password: '123', role: 'student' as const },
  ajay_singh_j: { password: '123', role: 'student' as const },
  murali_b: { password: '123', role: 'student' as const },
  barath_s: { password: '123', role: 'student' as const },
  irudhaya_jebiston_i: { password: '123', role: 'student' as const },
  praveen_m: { password: '123', role: 'student' as const },
  vickram_s: { password: '123', role: 'student' as const },
  dhaneshwaran_m: { password: '123', role: 'student' as const },
  ravivarman_g: { password: '123', role: 'student' as const },
  eniyavan_e: { password: '123', role: 'student' as const },
  inas_husayn_k: { password: '123', role: 'student' as const },
  mohankumar_s: { password: '123', role: 'student' as const },
  ezhilvendhan_t: { password: '123', role: 'student' as const },
  mageshwaran_m: { password: '123', role: 'student' as const },
  akshay_v: { password: '123', role: 'student' as const },
  santhosh_mugilan_: { password: '123', role: 'student' as const }

};

export interface AuthUser {
  username: string;
  role: 'student' | 'admin';
}

export class AuthService {
  private static readonly STORAGE_KEY = 'hostel_auth_user';

  static login(username: string, password: string): AuthUser | null {
    const credential = CREDENTIALS[username as keyof typeof CREDENTIALS];
    
    if (credential && credential.password === password) {
      const user: AuthUser = { username, role: credential.role };
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(user));
      return user;
    }
    
    return null;
  }

  static logout(): void {
    localStorage.removeItem(this.STORAGE_KEY);
  }

  static getCurrentUser(): AuthUser | null {
    try {
      const stored = localStorage.getItem(this.STORAGE_KEY);
      return stored ? JSON.parse(stored) : null;
    } catch {
      return null;
    }
  }

  static isAuthenticated(): boolean {
    return this.getCurrentUser() !== null;
  }

  static isAdmin(): boolean {
    const user = this.getCurrentUser();
    return user?.role === 'admin';
  }

  static isStudent(): boolean {
    const user = this.getCurrentUser();
    return user?.role === 'student';
  }
}